version: 2.{build}

cache:
  - C:\Users\appveyor\.m2 -> **\pom.xml

install:
  - set JAVA_HOME=C:\Program Files (x86)\Java\jdk1.8.0

environment:
  matrix:
  - RUN_ITS: true
    SQ_VERSION: LTS
  - RUN_ITS: true
    SQ_VERSION: LATEST_RELEASE

artifacts:
 - path: target\sonar-resharper-plugin.jar
   name: sonar-resharper-plugin-2.{build}-SNAPSHOT.JAR
   type: file

matrix:
  fast_finish: true

build_script:
  - ps: ./appveyor.ps1

test: off
